### ISSUE TITLE
CLI warnings are treated as errors

### ISSUE THREAD

**Issue by fzakfeld** [IPInfusion/ocnos-ansible-collection#4] opened 2023-06-02 10:54 UTC
When configuring breakouts, the CLI issues a warning. The ansible role treats this as an error and aborts the play, even though the configuration is valid and went successfully.

```
- name: Configure breakouts
  ipinfusion.ocnos.ocnos_config:
    lines:
      - port 8 breakout 4X25g
      - port 9 breakout 4X25g
```

Will result in:
```
"msg": "commit\r\r\n%% Warning : The interfaces & associated configs are deleted for this port/port-group \r\ncswitch_hostname(config)#"
```

A workaround is to use custom logic for failed_when and changed_when, but the ansible module should handle it correctly.
```
- name: Configure breakouts
  ipinfusion.ocnos.ocnos_config:
    lines:
      - port 8 breakout 4X25g
      - port 9 breakout 4X25g
  register: _result
  failed_when: _result.failed and 'msg' in _result and 'Warning' not in _result.msg
  changed_when: _result.changed or ('msg' in _result and 'Warning' in _result.msg)
```

**Comment by Saikiranlingala** [comment] 2024-11-25 05:28
hi @fzakfeld 
 
To investigate this issue further, we need additional information. If you’re still able to reproduce the problem, kindly share the exact steps you followed so we can analyze and resolve it effectively.

Looking forward to your response!

Thanks

**Comment by Saikiranlingala** [comment] 2024-12-12 07:31
Hi @fzakfeld 
We have been unable to reproduce this issue on our end, so we are closing it for now. If you encounter this issue again or can reproduce it, please don't hesitate to reach out to us with the necessary details for further analysis.

Thank you for your cooperation!

**Closed** 2024-12-13 12:23 UTC
